// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.insect.cbnu

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
    if (exception is FlutterError) {
        return listOf(
            exception.code,
            exception.message,
            exception.details
        )
    } else {
        return listOf(
            exception.javaClass.simpleName,
            exception.toString(),
            "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
        )
    }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
    val code: String,
    override val message: String? = null,
    val details: Any? = null
) : Throwable()

/**
 * Flutter → Android 또는 iOS 에 전달할 사용자 정보 클래스
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PigeonUserDetails (
    val uid: String? = null,
    val email: String? = null,
    val displayName: String? = null

) {
    companion object {
        @Suppress("UNCHECKED_CAST")
        fun fromList(list: List<Any?>): PigeonUserDetails {
            val uid = list[0] as String?
            val email = list[1] as String?
            val displayName = list[2] as String?
            return PigeonUserDetails(uid, email, displayName)
        }
    }
    fun toList(): List<Any?> {
        return listOf<Any?>(
            uid,
            email,
            displayName,
        )
    }
}
@Suppress("UNCHECKED_CAST")
private object AuthBridgeCodec : StandardMessageCodec() {
    override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
        return when (type) {
            128.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    PigeonUserDetails.fromList(it)
                }
            }
            else -> super.readValueOfType(type, buffer)
        }
    }
    override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
        when (value) {
            is PigeonUserDetails -> {
                stream.write(128)
                writeValue(stream, value.toList())
            }
            else -> super.writeValue(stream, value)
        }
    }
}

/**
 * Flutter → 플랫폼 호출을 위한 API 정의
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface AuthBridge {
    /** 로그인된 사용자 정보를 native로 전달 */
    fun sendUserDetails(details: PigeonUserDetails)

    companion object {
        /** The codec used by AuthBridge. */
        val codec: MessageCodec<Any?> by lazy {
            AuthBridgeCodec
        }
        /** Sets up an instance of `AuthBridge` to handle messages through the `binaryMessenger`. */
        @Suppress("UNCHECKED_CAST")
        fun setUp(binaryMessenger: BinaryMessenger, api: AuthBridge?) {
            run {
                val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_capston2025.AuthBridge.sendUserDetails", codec)
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val detailsArg = args[0] as PigeonUserDetails
                        var wrapped: List<Any?>
                        try {
                            api.sendUserDetails(detailsArg)
                            wrapped = listOf<Any?>(null)
                        } catch (exception: Throwable) {
                            wrapped = wrapError(exception)
                        }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
        }
    }
}
