// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import 'package:flutter/foundation.dart' show immutable;
import 'package:flutter/services.dart';

@immutable
class PigeonUserDetails {
  const PigeonUserDetails({
    this.uid,
    this.email,
    this.displayName,
  });

  final String? uid;
  final String? email;
  final String? displayName;

  Map<String, Object?> toMap() {
    return {
      'uid': uid,
      'email': email,
      'displayName': displayName,
    };
  }

  static PigeonUserDetails fromMap(Map<Object?, Object?> map) {
    return PigeonUserDetails(
      uid: map['uid'] as String?,
      email: map['email'] as String?,
      displayName: map['displayName'] as String?,
    );
  }
}

class _AuthBridgeCodec extends StandardMessageCodec {
  const _AuthBridgeCodec();

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return PigeonUserDetails.fromMap(readValue(buffer)! as Map<Object?, Object?>);
      default:
        return super.readValueOfType(type, buffer);
    }
  }

  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PigeonUserDetails) {
      buffer.putUint8(128);
      writeValue(buffer, value.toMap());
    } else {
      super.writeValue(buffer, value);
    }
  }
}

class AuthBridge {
  static const MessageCodec<Object?> codec = _AuthBridgeCodec();

  Future<void> sendUserDetails(PigeonUserDetails details) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.flutter_capston2025.AuthBridge.sendUserDetails',
      codec,
    );
    final result = await channel.send(<Object?>[details]);
    if (result is Map && result.containsKey('error')) {
      final error = result['error'] as Map;
      throw PlatformException(
        code: error['code'],
        message: error['message'],
        details: error['details'],
      );
    }
  }
}
