// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyTNnJKLNDdTPRKIoQ-1IsksCtUJA9xcs',
    appId: '1:964812499160:web:790c6f964513310fed4fad',
    messagingSenderId: '964812499160',
    projectId: 'cbnu-aed65',
    authDomain: 'cbnu-aed65.firebaseapp.com',
    storageBucket: 'cbnu-aed65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnCCYqHhS8QH0iD16txRcXp_5n4B3hJ_A',
    appId: '1:964812499160:android:e6884de08030b882ed4fad',
    messagingSenderId: '964812499160',
    projectId: 'cbnu-aed65',
    storageBucket: 'cbnu-aed65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoxK9rUUyhneuxecZp27gslTs5b-eFr3U',
    appId: '1:964812499160:ios:99b674840fe40121ed4fad',
    messagingSenderId: '964812499160',
    projectId: 'cbnu-aed65',
    storageBucket: 'cbnu-aed65.firebasestorage.app',
    iosBundleId: 'com.example.flutterCapston2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoxK9rUUyhneuxecZp27gslTs5b-eFr3U',
    appId: '1:964812499160:ios:99b674840fe40121ed4fad',
    messagingSenderId: '964812499160',
    projectId: 'cbnu-aed65',
    storageBucket: 'cbnu-aed65.firebasestorage.app',
    iosBundleId: 'com.example.flutterCapston2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyTNnJKLNDdTPRKIoQ-1IsksCtUJA9xcs',
    appId: '1:964812499160:web:43c663a8fd3b5a27ed4fad',
    messagingSenderId: '964812499160',
    projectId: 'cbnu-aed65',
    authDomain: 'cbnu-aed65.firebaseapp.com',
    storageBucket: 'cbnu-aed65.firebasestorage.app',
  );
}
